/** @jsxImportSource theme-ui */
import React from 'react'
import Head from 'next/head'
import Navigation from '../../components/Navigation'

const Page: React.FC = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header
        sx={{
          height: '60px',
          width: '100vw',
          bg: 'primary',
          borderBottom: '1px solid',
          borderColor: 'primary',
        }}
      >
        <Navigation />
      </header>
      <main
        sx={{ height: `calc(100vh - 60px - 30px)`, variant: 'containers.page' }}
      >
        {children}
      </main>
      <footer sx={{ height: '30px', textAlign: 'center' }}>
        footer content
      </footer>
    </div>
  )
}

export default Page
