import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

type Props = {
  content: {
    main: string;
    footer: string;
  };
};

const Home: NextPage<Props> = ({ content }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Intro Next.JS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>{content.main}</main>

      <footer className={styles.footer}>{content.footer}</footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = () => {
  return {
    props: {
      content: {
        main: 'main content',
        footer: 'footer content',
      },
    },
  };
};

export default Home;
